# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b6b61b054dbead98d3d4b71ebd25217ef6bf226d95d5e30d51ddd14c194b533644041abf4e44c0bebae591c27a92bff0fb9416588b5058bf72336a11f2447769

test:
  secret_key_base: 2c0e517570bbc43db0358db8ca7c6c220aeb391912acbfedb8e478d42a383659fea7dadfc6d27591e57e9aea0d1474fc6ebf7ed6b4a8e2fcc08589b4b5402cfe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
